import type { Pitch } from "./types";

export const pitches: Pitch[] = [
  {
    id: 1,
    name: "Sportpark-Umkirch",
    location: "Umkirch",
    rating: 5.0,
    maxPlayers: 10,
    price: "$$$",
    restaurant: true,
    outdoor: false,
    indoor: true,
    parking: true,
    lights: true,
    turf: false,
    imageUrl: "./umkirch-logo.png",
    infoUrl: "https://black-forest-freizeit.de/soccer/",
    moreInfo: {
      oneHourSessionPrice: "82 Euro",
      twoHourSessionPrice: "164 Euro",
    },
  },
  {
    id: 2,
    name: "ESV Freiburg",
    location: "Sankt Georgen",
    rating: 3.5,
    maxPlayers: 14,
    price: "$",
    restaurant: true,
    outdoor: true,
    indoor: false,
    parking: true,
    lights: false,
    turf: false,
    imageUrl: "./umkirch-logo.png",
    infoUrl: "",
    moreInfo: {
      oneHourSessionPrice: "82 Euro",
      twoHourSessionPrice: "164 Euro",
    },
  },
  {
    id: 3,
    name: "Seepark",
    location: "Mooswald",
    rating: 2,
    maxPlayers: 14,
    price: "Free",
    restaurant: false,
    outdoor: true,
    indoor: false,
    parking: true,
    lights: false,
    turf: true,
    imageUrl: "./umkirch-logo.png",
    infoUrl: "",
    moreInfo: {
      oneHourSessionPrice: "Free",
    },
  },
  {
    id: 4,
    name: "PSV Freiburg",
    location: "Sankt Georgen",
    rating: 5,
    maxPlayers: 14,
    price: "$$",
    restaurant: true,
    outdoor: true,
    indoor: false,
    parking: true,
    lights: true,
    turf: true,
    imageUrl: "./umkirch-logo.png",
    infoUrl: "",
    moreInfo: {
      oneHourSessionPrice: "82 Euro",
      twoHourSessionPrice: "164 Euro",
    },
  },
];
